### ISSUE TITLE
Right command seems to be always pressed

### ISSUE THREAD

**Issue by kov** [knazarov/homebrew-qemu-virgl#14]
I tried installing Fedora but the keyboard would not respond. After the installation booted automatically I started poking around a bit and it seems if I hold the command key to the right of the spacebar things work as expected. I guess I'm hitting the bug that is mentioned in this page:

https://gist.github.com/akihikodaki/87df4149e7ca87f18dc56807ec5a1bc5

```
ui/cocoa

<snip>
    A bug which keeps e.g. command key pressed is fixed.
```

By the way, I tried adding a usb kbd instead to see if would make any difference and got this:

qemu-system-aarch64: -device usb-kbd: No 'usb-bus' bus found for device 'usb-kbd'

Is qemu being built without USB or something? The options seem to be there in --help but I have no clue why it doesn't like it.

**Comment by Twilighttony** [comment]
I am having the same issue. When trying to install a distro that needs keyboard input at the boot screen to access it, it doesn't respond until past Wayland/X11

**Comment by knazarov** [comment]
You can try to run with:

```
-device qemu-xhci
-device usb-kbd
```

And don’t forget to remove `-device virtio-keyboard-pci`

**Comment by Twilighttony** [comment]
> -device qemu-xhci
> -device usb-kbd

Thanks that worked!

**Comment by knazarov** [comment]
@kov did you have success with this?

**Comment by kov** [comment]
Sorry, yes it works for me as well with a usb keyboard, thanks!
