### ISSUE TITLE
keyboard not working?

### ISSUE THREAD

**Issue by phirestalker** [knazarov/homebrew-qemu-virgl#22]
I am not sure if I am doing something wrong or not. I used the commandline for M1 macs, only I used a debian buster install cd. I am at the menu and I press enter, but nothing happens. Other keys don't seem to be working either. I tried clicking in the window, but that only seems to capture mouse input and does nothing about the keyboard.

Are there other options I can try besides virtio-keyboard-pci?

**Comment by knazarov** [comment]
You can try:

```
-device qemu-xhci
-device usb-kbd
```

**Comment by phirestalker** [comment]
That worked. Thanks
