### ISSUE TITLE
brew install qemu-virgl fails

### ISSUE THREAD

**Issue by CuB0** [knazarov/homebrew-qemu-virgl#25]
When I issue the command, it installs some packages but then fails with:

**curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "libangle"
Download failed: https://github.com/knazarov/homebrew-qemu-virgl/releases/download/libangle-20210315.1/libangle-20210315.1.big_sur.bottle.tar.gz
**

Looking with curl seems that libangle tarball is missing from the url reported in the formula.

Thanks in advance for your support

**Comment by davidvasandani** [comment]
`libangle-20210315.1.big_sur.bottle.gz` should be `tar.gz`

1. Download [libangle](https://github.com/knazarov/homebrew-qemu-virgl/releases/download/libangle-20210315.1/libangle-20210315.1.big_sur.bottle.gz) from the releases page.
2. Rename the file to tar.gz
3. Serve the file using some local http server
2. Edit the homebrew formula `brew edit knazarov/qemu-virgl/libangle`
```
  bottle do
    root_url "http://localhost:8000"
    sha256 cellar: :any, big_sur:       "e9aa9442083ef1eb5b3e760170d941b1ab4d8df521d97155afdf307619bd6351"
```
5. Install libangle: `brew install knazarov/qemu-virgl/libangle`
6. Install qemu-virgl: `brew install knazarov/qemu-virgl/qemu-virgl`

**Comment by knazarov** [comment]
I’ve updated the file extension in the libangle release. Not sure how it could have happened. Please try again
