### ISSUE TITLE
brew install fails because url for FD12FLOPPY.zip returns 403

### ISSUE THREAD

**Issue by vivlim** [knazarov/homebrew-qemu-virgl#29]
I am trying to install this via `brew install knazarov/qemu-virgl/qemu-virgl` but get the following error:

```
...
==> Downloading https://raw.githubusercontent.com/knazarov/homebrew-qemu-virgl/35703a784e5
Already downloaded: /Users/vivlim/Library/Caches/Homebrew/downloads/7f3909a48ae9baefa8343802d50a3566327447b3cc1a0caee1829a19790045a7--qemu-v03.diff
==> Downloading https://raw.githubusercontent.com/knazarov/homebrew-qemu-virgl/fa3b5dcc2f0
Already downloaded: /Users/vivlim/Library/Caches/Homebrew/downloads/aee03539d98bfad39184807069b9daae6d28242e1f26c92d5f5d7d2d33e6bd4b--qemu-edid-v01.diff
==> Downloading https://dl.bintray.com/homebrew/mirror/FD12FLOPPY.zip

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "qemu-virgl--test-image"
Download failed: https://dl.bintray.com/homebrew/mirror/FD12FLOPPY.zip
```

Is there another location to get this file from?

**Comment by pztrn** [comment]
Probably https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/ ?

**Comment by knazarov** [comment]
Merged the pull request. It looks like the upstream qemu formula has changed its URL as well.

**Comment by Aries0d0f** [comment]
The link of assets file `FD12FLOPPY.zip` changed again to https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/official/FD12FLOPPY.zip.

**Comment by aselvan** [comment]
From the above post, I understand the link changed again for the test image. Is there a workaround anyone knows to get past this? I don't really need the sample image.

```
Error: qemu-virgl: Failed to download resource "qemu-virgl--test-image"
Download failed: https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/FD12FLOPPY.zip
```

**Comment by Aries0d0f** [comment]
> From the above post, I understand the link changed again for the test image. Is there a workaround anyone knows to get past this? I don't really need the sample image.
> 
> ```
> Error: qemu-virgl: Failed to download resource "qemu-virgl--test-image"
> Download failed: https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/FD12FLOPPY.zip
> ```

There is a simple workaround:
`Homebrew` will clone every repo before installation, so when you run it once (even failed with errors like the above), it was already located on your computer.

In my case, it was `/opt/homebrew/Library/Taps/knazarov/homebrew-qemu-virgl`.
So you can manually change the URL in file `Fomular/qemu-virgl.rb` at line 32 (or commented out L31:L34 but I haven't tested this so keep it in theory), then run `brew install qemu-virgl` again.

BTW PR. #85, #93, and #94 did a great job on solving this but haven't been merged by the owner.
