### ISSUE TITLE
Additional documentation for newbies

### ISSUE THREAD

**Issue by GlenHenshaw** [knazarov/homebrew-qemu-virgl#3]
For those of us who want to run Linux on M1 but are completely new to QEMU, an example of how to invoke the software, including a full command line set of options that work, would be very helpful. It isn't immediately obvious where the various QEMU support files and images get installed, for instance.

**Comment by knazarov** [comment]
Hi @GlenHenshaw,

I have one problem left for this to start working on an M1 mac (libepoxy can’t find the OpenGL library, because homebrew on M1 has different locations for them). I hope to solve it on Monday, and then I’ll put down a complete guide.

**Comment by knazarov** [comment]
Done. Now there are instructions for both x86 and arm.
