### ISSUE TITLE
no keys work on boot

### ISSUE THREAD

**Issue by Colourzz** [knazarov/homebrew-qemu-virgl#33]
none of the keys work when I boot into the screen that gives you the try ubuntu, install ubuntu etc.

I'm running big sur 11.4

I would appreciate help, thank you

**Comment by knazarov** [comment]
You can probably use:

```
-device qemu-xhci
-device usb-kbd
```

instead of `-device virtio-mouse-pci` at the command line. I probably should change it in README. For some people, the bios doesn’t detect this properly.

**Comment by knazarov** [comment]
I've added the usage of `usb-kbd` to README.md to make those issues not appear for new users.
