### ISSUE TITLE
some m1 mini notes

### ISSUE THREAD

**Issue by hexdump0815** [knazarov/homebrew-qemu-virgl#4]
hi,

first a big thank you for your effort (and the same of course goes to the original author of the virgl setup) to make it so easy to set this up!

for using it on a m1 mac mini i had to exchange:
```
         -device virtio-keyboard-pci \
         -device virtio-mouse-pci \
```
with
```
         -device qemu-xhci \
         -device usb-kbd \
         -device usb-tablet \
```
otherwise the keyboard did not work inside of the qemu bios ... also i had to set
```
export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib
```
it looks like you adressed this somehow already, but i did a brew reinstall at the state of git comit 14a3b8ea06854ba6e40526e11c0be0bc69ca8734 (after having played around with it a few days ago already) and the above export is still required

with this setup the booted qemu did not find neither the cdrom nor the disk to boot from and ended up trying to boot from the network. to get out of this i had to enter "escape" quickly after starting qemu and then set the boot drive in there to i think misc 2 for the disk and misc 4 for the cdrom - then it booted well as it should from cdrom or disk image. i got this fixed by changing the boot order properly in the qemu bios and saving it.

thanks a lot once more and best wishes - hexdump

**Comment by knazarov** [comment]
Hi @hexdump0815,

Could you please post here the output of qemu when running without `DYLD_FALLBACK_PATH`? It should print the EGL libraries it tried to load. It will also print the fallback path so we can check why my fix doesn't work.

**Comment by hexdump0815** [comment]
it does not print anything beyond the dynamic library loading error:
```
Couldn't open libEGL.dylib: dlopen(libEGL.dylib, 5): image not found
```
maybe the brew reinstall did not really catch your latest version?

here is some more debug info in case it might help:
```
% /opt/homebrew/bin/brew shellenv
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
% ls -l /opt/homebrew/lib/libEGL.dylib
lrwxr-xr-x  1 username  admin  46 17 Mär 19:39 /opt/homebrew/lib/libEGL.dylib -> ../Cellar/libangle/20210315.1/lib/libEGL.dylib
% ls -l /opt/homebrew/Cellar/libangle/20210315.1/lib/libEGL.dylib
-r--r--r--  1 username  admin  177104 17 Mär 19:39 /opt/homebrew/Cellar/libangle/20210315.1/lib/libEGL.dylib
```

**Comment by knazarov** [comment]
Yes, it looks like it didn't install the latest version. Try doing a `brew tap --force-auto-update knazarov/qemu-virgl`, then `brew reinstall -s libepoxy-angle`

**Comment by hexdump0815** [comment]
thanks @knazarov - that fixed the problem with libEGL

is there a way to tell the bios in qemu to use another device as default boot device? on my system misc 3 is the hd and misc 4 the cdrom - the default misc device will fail ...

**Comment by knazarov** [comment]
I'm glad to hear that you've got it working!

As for the boot order - theoretically, the purpose of `edk2-arm-vars.fd` is to store EFI configuration variables, including the boot order. After you change settings in the EFI, they are reflected in this file (hence it's mounted as read-write). By default it should be organized in a way to make the cdrom as a primary boot device. 

I've rented a M1 MacMini in the cloud and tested on it, and it works for me. The way to debug this would be to look into how qemu builds this file and try to understand why it may not choose cdrom as primary on your system. It may have something to do with the identifiers assigned to devices (very likely). I'd assume that for those of users for whom this works, get the cdrom device id as expected by the default EFI vars.

**Comment by hexdump0815** [comment]
thanks a lot for the explaination and once more for all your effort!

**Comment by knazarov** [comment]
I have one more thing you may try to do to boot from iso. Maybe you should add an option `-boot d` when running with the CD image. It would be great if you can try from scratch with fresh `edk2-arm-vars.fd` and a clean image, and specify this option.

**Comment by hexdump0815** [comment]
i tried it from scratch and that seems to help - with -boot d it seems to work well :)

**Comment by knazarov** [comment]
Closing the issue as we've figured out the problem. I've also updated the instruction to include the `-boot d` option.
