### ISSUE TITLE
when I run glmark2 it still shows GL_RENDERER: llvmpipe

### ISSUE THREAD

**Issue by asanoic** [knazarov/homebrew-qemu-virgl#43]

**Comment by knazarov** [comment]
I've met this problem after rebasing to the latest virgl patchset. The name of the accelerated vga device was changed. You now should pass `-device virtio-gpu-gl-pci` on M1 macs, and `-device virtio-vga-gl` on x86.

I've noticed that I didn't change it in the README properly (just fixed it).

**Comment by asanoic** [comment]
I made a screenshot, on ubuntu it shows as llvmpipe.

![Screen Shot 2021-08-18 at 5 48 09 PM](https://user-images.githubusercontent.com/70875479/129982945-8689216a-5034-44b2-897f-7bca6a5539df.png)

**Comment by knazarov** [comment]
Could you please paste the full command line you run qemu with?
