### ISSUE TITLE
after add Clipboard sharing start parameter, qemu complains 'qemu-vdagent' is not a valid char driver name

### ISSUE THREAD

**Issue by lzq420241** [knazarov/homebrew-qemu-virgl#47]
here are my macbook info:
<img width="286" alt="Screen Shot 2021-08-17 at 12 05 23 AM" src="https://user-images.githubusercontent.com/3714278/129594268-ea9ba513-43ee-4f49-b379-663b0d156aea.png">
<img width="393" alt="Screen Shot 2021-08-17 at 12 06 39 AM" src="https://user-images.githubusercontent.com/3714278/129594334-71b4b7b9-69f5-4415-8b58-d27498c0df50.png">

I installed an ubuntu 20.04 guest, 
when run qemu with the following 
        ` -chardev qemu-vdagent,id=spice,name=vdagent,clipboard=on 
         -device virtio-serial-pci 
         -device virtserialport,chardev=spice,name=com.redhat.spice.0`
the startup failed, the output is:
qemu-system-x86_64: -chardev qemu-vdagent,id=spice,name=vdagent,clipboard=on: 'qemu-vdagent' is not a valid char driver name

**Comment by lzq420241** [comment]
Should I run qemu with clipboard sharing when I built the guest from cdrom?
The guest image file was made from an offical qemu.

**Comment by knazarov** [comment]
Hi @lzq420241 !

Try rebuilding from source like this:

```
brew reinstall -s qemu-virgl
```

It’s possible that you’ve grabbed a binary release that lags a bit behind.

Regarding the image - it doesn’t matter how you built it — the image from regular qemu will do.

**Comment by lzq420241** [comment]
Thanks!
