### ISSUE TITLE
Can't resize window on M1

### ISSUE THREAD

**Issue by DUOLabs333** [knazarov/homebrew-qemu-virgl#52]
I've tried changing the VM window size, but can't.

**Comment by DUOLabs333** [comment]
i just realized that you have to change the resolution from within the VM, though I don't know if this is a proper solution.

**Comment by knazarov** [comment]
Another way is when the vm starts, in the MacOS menu you need to pick View->Zoom To Fit. Then you'll be able to resize the window.

**Comment by DUOLabs333** [comment]
Oh, that works perfectly! It's a bit buggy, but it's the best option there is.
