### ISSUE TITLE
[Issue] Can't use USB C ethernet with qemu

### ISSUE THREAD

**Issue by Twilighttony** [knazarov/homebrew-qemu-virgl#57]
Hello, I am trying to use qemu and I noticed that when I plug in my ethernet enabled dock, I can't connect to the internet in my VM but I can just fine in my host machine.

**Comment by DUOLabs333** [comment]
Did you add ```-netdev vmnet-macos,id=net0,mode=bridged,ifname=en0 \
-device virtio-net,netdev=net0,mac=52:54:00:c9:18:27```

**Comment by Twilighttony** [comment]
> Did you add `-netdev vmnet-macos,id=net0,mode=bridged,ifname=en0 \ -device virtio-net,netdev=net0,mac=52:54:00:c9:18:27`

Thanks. That works!
