### ISSUE TITLE
Host doesn't support requested feature

### ISSUE THREAD

**Issue by asdfghjkl403622** [knazarov/homebrew-qemu-virgl#59]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.invpcid [bit 10]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EDX.spec-ctrl [bit 26]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:EDX.rdtscp [bit 27]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.x2apic [bit 21]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.01H:ECX.tsc-deadline [bit 24]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EBX.invpcid [bit 10]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.07H:EDX.spec-ctrl [bit 26]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:EDX.rdtscp [bit 27]
Couldn't open libEGL.dylib: dlopen(libEGL.dylib, 5): image not found
zsh: abort      qemu-system-x86_64 -machine accel=hvf -cpu Haswell-v4 -smp 2 -m 4G -device

**Comment by asdfghjkl403622** [comment]
`qemu-system-x86_64: unsupported machine type`

**Comment by asdfghjkl403622** [comment]
what should I change?

**Comment by asdfghjkl403622** [comment]
[end of kernel panic] system is deadlocked on memory

**Comment by asdfghjkl403622** [comment]
should I also give it more threads with `-smp $(nproc)`?

**Comment by DUOLabs333** [comment]
`-smp 4`

**Comment by asdfghjkl403622** [comment]
it works!

**Comment by asdfghjkl403622** [comment]
qemu-system-x86_64 \
         -device intel-hda -device hda-output \
         -device qemu-xhci \
         -device virtio-vga-gl \
         -device usb-kbd \
         -device virtio-net-pci,netdev=net \
         -device virtio-mouse-pci \
         -display cocoa,gl=es \
         -netdev user,id=net,ipv6=off \
         -drive "if=virtio,format=raw,file=hdd.raw,discard=on" \
         -cdrom Fedora-Workstation-Live-x86_64-34-1.2.iso \
         -boot d \
         -m 4G \
         -smp 4

**Comment by asdfghjkl403622** [comment]
command I used for people in the future

**Comment by jonathancross** [comment]
@asdfghjkl403622 

> You should close this now.
