### ISSUE TITLE
Changes compared to QEMU 6.1 from Homebrew

### ISSUE THREAD

**Issue by SebDanielsson** [knazarov/homebrew-qemu-virgl#60]
Is there a way to track which changes that you have made compared to the latest QEMU 6.1 for Apple Silicon systems?

**Comment by knazarov** [comment]
It's not easy. You can track changes here: https://github.com/akihikodaki/qemu/tree/macos and calculate the base revision with the official qemu tree. Which is what I do when preparing the next patchset. The qemu-virgl formula always lists the base revision in the git checkout arguments.

Anyway, there will be a new version soon which is rebased on top of the latest qemu from upstream.

**Comment by DUOLabs333** [comment]
This should probably be closed now.
