### ISSUE TITLE
`opengl is not available`

### ISSUE THREAD

**Issue by bkchr** [knazarov/homebrew-qemu-virgl#70]
Hey, when trying to use `virtio-gpu-gl-pci` with `-display cocoa,gl=off` I just get the error message:

```
qemu-system-aarch64: -device virtio-gpu-gl-pci: opengl is not available
```

Any idea what I could be missing? Do I may need to enable Opengl in Mac os somewhere?

**Comment by DUOLabs333** [comment]
You must use `-display cocoa,gl=es`

**Comment by bkchr** [comment]
Why? The original gist lists 3 different values.

**Comment by bkchr** [comment]
See https://gist.github.com/akihikodaki/87df4149e7ca87f18dc56807ec5a1bc5#choosing-opengl-profile

**Comment by DUOLabs333** [comment]
Also, is the `device` listed before or after the `display`?

**Comment by bkchr** [comment]
Before.

**Comment by DUOLabs333** [comment]
Does using `gl=es` work?

**Comment by bkchr** [comment]
Yes that works, but I get a lot of unsupported shader errors. So, I wanted to try one of the other.

**Comment by DUOLabs333** [comment]
I get the same thing, but it continues to works, so I don't mind it. Does
vmnet work for you?

**Comment by DUOLabs333** [comment]
Does `gl=core` work?
