### ISSUE TITLE
Update to latest patchset?

### ISSUE THREAD

**Issue by akirakyle** [knazarov/homebrew-qemu-virgl#74]
The latest changes to https://github.com/akihikodaki/qemu/tree/macos aren't yet included in this formula

**Comment by DUOLabs333** [comment]
He makes the patchfile every QEMU release -- it will probably be merged in when QEMU has a new release.

**Comment by DUOLabs333** [comment]
However, I am testing a fork of just using `akihikodaki`'s repositories directly.

**Comment by DUOLabs333** [comment]
However, I am running into the problem where since I have this repository enabled, it interferes with my testing.

**Comment by DUOLabs333** [comment]
@knazarov Have you thought of just using the repositories directly at versioned commits, instead of using diffs?

**Comment by DUOLabs333** [comment]
I'm going to test it out today, and will post it on Github once I get it working.

**Comment by DUOLabs333** [comment]
Are you still interested in something like that?
