### ISSUE TITLE
Nested Virtualization

### ISSUE THREAD

**Issue by DUOLabs333** [knazarov/homebrew-qemu-virgl#79]
I'm running an Arch VM on my M1 Macbook. However, now i want to run a VM in my VM. However, when I try, I get "HYP mode not available"

**Comment by UmarAhmed129** [comment]
https://patchwork.kernel.org/project/linux-arm-kernel/patch/20171128151819.18669-1-ard.biesheuvel@linaro.org/

**Comment by DUOLabs333** [comment]
Does this mean that it will be applied soon, or I have to compile it myself?
